/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SundayReviewRouteImport } from './routes/sunday-review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ElderRouteImport } from './routes/elder'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElderIndexRouteImport } from './routes/elder.index'
import { Route as ElderSettingsRouteImport } from './routes/elder.settings'
import { Route as ElderPastoralCareRouteImport } from './routes/elder.pastoral-care'
import { Route as ElderMeetingsRouteImport } from './routes/elder.meetings'
import { Route as ElderArchiveRouteImport } from './routes/elder.archive'
import { Route as CalendarPublicRouteImport } from './routes/calendar_.public'
import { Route as CalendarPlanningRouteImport } from './routes/calendar_.planning'
import { Route as ElderMeetingsIndexRouteImport } from './routes/elder.meetings.index'
import { Route as ElderMeetingsMeetingIdRouteImport } from './routes/elder.meetings.$meetingId'
import { Route as CalendarPlanningReviewRouteImport } from './routes/calendar_.planning.review'
import { Route as CalendarPlanningSubmissionIdRouteImport } from './routes/calendar_.planning.$submissionId'
import { Route as ApiGoogleOauthCallbackRouteImport } from './routes/api/google.oauth-callback'
import { Route as ApiPublicHooksSundayReviewNudgeRouteImport } from './routes/api/public/hooks.sunday-review-nudge'
import { Route as ApiPublicHooksActionItemsDigestRouteImport } from './routes/api/public/hooks.action-items-digest'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayReviewRoute = SundayReviewRouteImport.update({
  id: '/sunday-review',
  path: '/sunday-review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderRoute = ElderRouteImport.update({
  id: '/elder',
  path: '/elder',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderIndexRoute = ElderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElderRoute,
} as any)
const ElderSettingsRoute = ElderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ElderRoute,
} as any)
const ElderPastoralCareRoute = ElderPastoralCareRouteImport.update({
  id: '/pastoral-care',
  path: '/pastoral-care',
  getParentRoute: () => ElderRoute,
} as any)
const ElderMeetingsRoute = ElderMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => ElderRoute,
} as any)
const ElderArchiveRoute = ElderArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ElderRoute,
} as any)
const CalendarPublicRoute = CalendarPublicRouteImport.update({
  id: '/calendar_/public',
  path: '/calendar/public',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarPlanningRoute = CalendarPlanningRouteImport.update({
  id: '/calendar_/planning',
  path: '/calendar/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderMeetingsIndexRoute = ElderMeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElderMeetingsRoute,
} as any)
const ElderMeetingsMeetingIdRoute = ElderMeetingsMeetingIdRouteImport.update({
  id: '/$meetingId',
  path: '/$meetingId',
  getParentRoute: () => ElderMeetingsRoute,
} as any)
const CalendarPlanningReviewRoute = CalendarPlanningReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CalendarPlanningRoute,
} as any)
const CalendarPlanningSubmissionIdRoute =
  CalendarPlanningSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => CalendarPlanningRoute,
  } as any)
const ApiGoogleOauthCallbackRoute = ApiGoogleOauthCallbackRouteImport.update({
  id: '/api/google/oauth-callback',
  path: '/api/google/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSundayReviewNudgeRoute =
  ApiPublicHooksSundayReviewNudgeRouteImport.update({
    id: '/api/public/hooks/sunday-review-nudge',
    path: '/api/public/hooks/sunday-review-nudge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksActionItemsDigestRoute =
  ApiPublicHooksActionItemsDigestRouteImport.update({
    id: '/api/public/hooks/action-items-digest',
    path: '/api/public/hooks/action-items-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/decisions': typeof DecisionsRoute
  '/elder': typeof ElderRouteWithChildren
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/missions': typeof MissionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/sunday-review': typeof SundayReviewRoute
  '/trends': typeof TrendsRoute
  '/users': typeof UsersRoute
  '/calendar/planning': typeof CalendarPlanningRouteWithChildren
  '/calendar/public': typeof CalendarPublicRoute
  '/elder/archive': typeof ElderArchiveRoute
  '/elder/meetings': typeof ElderMeetingsRouteWithChildren
  '/elder/pastoral-care': typeof ElderPastoralCareRoute
  '/elder/settings': typeof ElderSettingsRoute
  '/elder/': typeof ElderIndexRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/calendar/planning/$submissionId': typeof CalendarPlanningSubmissionIdRoute
  '/calendar/planning/review': typeof CalendarPlanningReviewRoute
  '/elder/meetings/$meetingId': typeof ElderMeetingsMeetingIdRoute
  '/elder/meetings/': typeof ElderMeetingsIndexRoute
  '/api/public/hooks/action-items-digest': typeof ApiPublicHooksActionItemsDigestRoute
  '/api/public/hooks/sunday-review-nudge': typeof ApiPublicHooksSundayReviewNudgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/decisions': typeof DecisionsRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/missions': typeof MissionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/sunday-review': typeof SundayReviewRoute
  '/trends': typeof TrendsRoute
  '/users': typeof UsersRoute
  '/calendar/planning': typeof CalendarPlanningRouteWithChildren
  '/calendar/public': typeof CalendarPublicRoute
  '/elder/archive': typeof ElderArchiveRoute
  '/elder/pastoral-care': typeof ElderPastoralCareRoute
  '/elder/settings': typeof ElderSettingsRoute
  '/elder': typeof ElderIndexRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/calendar/planning/$submissionId': typeof CalendarPlanningSubmissionIdRoute
  '/calendar/planning/review': typeof CalendarPlanningReviewRoute
  '/elder/meetings/$meetingId': typeof ElderMeetingsMeetingIdRoute
  '/elder/meetings': typeof ElderMeetingsIndexRoute
  '/api/public/hooks/action-items-digest': typeof ApiPublicHooksActionItemsDigestRoute
  '/api/public/hooks/sunday-review-nudge': typeof ApiPublicHooksSundayReviewNudgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/decisions': typeof DecisionsRoute
  '/elder': typeof ElderRouteWithChildren
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/missions': typeof MissionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/sunday-review': typeof SundayReviewRoute
  '/trends': typeof TrendsRoute
  '/users': typeof UsersRoute
  '/calendar_/planning': typeof CalendarPlanningRouteWithChildren
  '/calendar_/public': typeof CalendarPublicRoute
  '/elder/archive': typeof ElderArchiveRoute
  '/elder/meetings': typeof ElderMeetingsRouteWithChildren
  '/elder/pastoral-care': typeof ElderPastoralCareRoute
  '/elder/settings': typeof ElderSettingsRoute
  '/elder/': typeof ElderIndexRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/calendar_/planning/$submissionId': typeof CalendarPlanningSubmissionIdRoute
  '/calendar_/planning/review': typeof CalendarPlanningReviewRoute
  '/elder/meetings/$meetingId': typeof ElderMeetingsMeetingIdRoute
  '/elder/meetings/': typeof ElderMeetingsIndexRoute
  '/api/public/hooks/action-items-digest': typeof ApiPublicHooksActionItemsDigestRoute
  '/api/public/hooks/sunday-review-nudge': typeof ApiPublicHooksSundayReviewNudgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/decisions'
    | '/elder'
    | '/finance'
    | '/forgot-password'
    | '/login'
    | '/meeting'
    | '/missions'
    | '/reset-password'
    | '/rooms'
    | '/settings'
    | '/sunday-review'
    | '/trends'
    | '/users'
    | '/calendar/planning'
    | '/calendar/public'
    | '/elder/archive'
    | '/elder/meetings'
    | '/elder/pastoral-care'
    | '/elder/settings'
    | '/elder/'
    | '/api/google/oauth-callback'
    | '/calendar/planning/$submissionId'
    | '/calendar/planning/review'
    | '/elder/meetings/$meetingId'
    | '/elder/meetings/'
    | '/api/public/hooks/action-items-digest'
    | '/api/public/hooks/sunday-review-nudge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/decisions'
    | '/finance'
    | '/forgot-password'
    | '/login'
    | '/meeting'
    | '/missions'
    | '/reset-password'
    | '/rooms'
    | '/settings'
    | '/sunday-review'
    | '/trends'
    | '/users'
    | '/calendar/planning'
    | '/calendar/public'
    | '/elder/archive'
    | '/elder/pastoral-care'
    | '/elder/settings'
    | '/elder'
    | '/api/google/oauth-callback'
    | '/calendar/planning/$submissionId'
    | '/calendar/planning/review'
    | '/elder/meetings/$meetingId'
    | '/elder/meetings'
    | '/api/public/hooks/action-items-digest'
    | '/api/public/hooks/sunday-review-nudge'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/decisions'
    | '/elder'
    | '/finance'
    | '/forgot-password'
    | '/login'
    | '/meeting'
    | '/missions'
    | '/reset-password'
    | '/rooms'
    | '/settings'
    | '/sunday-review'
    | '/trends'
    | '/users'
    | '/calendar_/planning'
    | '/calendar_/public'
    | '/elder/archive'
    | '/elder/meetings'
    | '/elder/pastoral-care'
    | '/elder/settings'
    | '/elder/'
    | '/api/google/oauth-callback'
    | '/calendar_/planning/$submissionId'
    | '/calendar_/planning/review'
    | '/elder/meetings/$meetingId'
    | '/elder/meetings/'
    | '/api/public/hooks/action-items-digest'
    | '/api/public/hooks/sunday-review-nudge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DecisionsRoute: typeof DecisionsRoute
  ElderRoute: typeof ElderRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MeetingRoute: typeof MeetingRoute
  MissionsRoute: typeof MissionsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  SundayReviewRoute: typeof SundayReviewRoute
  TrendsRoute: typeof TrendsRoute
  UsersRoute: typeof UsersRoute
  CalendarPlanningRoute: typeof CalendarPlanningRouteWithChildren
  CalendarPublicRoute: typeof CalendarPublicRoute
  ApiGoogleOauthCallbackRoute: typeof ApiGoogleOauthCallbackRoute
  ApiPublicHooksActionItemsDigestRoute: typeof ApiPublicHooksActionItemsDigestRoute
  ApiPublicHooksSundayReviewNudgeRoute: typeof ApiPublicHooksSundayReviewNudgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-review': {
      id: '/sunday-review'
      path: '/sunday-review'
      fullPath: '/sunday-review'
      preLoaderRoute: typeof SundayReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder': {
      id: '/elder'
      path: '/elder'
      fullPath: '/elder'
      preLoaderRoute: typeof ElderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/': {
      id: '/elder/'
      path: '/'
      fullPath: '/elder/'
      preLoaderRoute: typeof ElderIndexRouteImport
      parentRoute: typeof ElderRoute
    }
    '/elder/settings': {
      id: '/elder/settings'
      path: '/settings'
      fullPath: '/elder/settings'
      preLoaderRoute: typeof ElderSettingsRouteImport
      parentRoute: typeof ElderRoute
    }
    '/elder/pastoral-care': {
      id: '/elder/pastoral-care'
      path: '/pastoral-care'
      fullPath: '/elder/pastoral-care'
      preLoaderRoute: typeof ElderPastoralCareRouteImport
      parentRoute: typeof ElderRoute
    }
    '/elder/meetings': {
      id: '/elder/meetings'
      path: '/meetings'
      fullPath: '/elder/meetings'
      preLoaderRoute: typeof ElderMeetingsRouteImport
      parentRoute: typeof ElderRoute
    }
    '/elder/archive': {
      id: '/elder/archive'
      path: '/archive'
      fullPath: '/elder/archive'
      preLoaderRoute: typeof ElderArchiveRouteImport
      parentRoute: typeof ElderRoute
    }
    '/calendar_/public': {
      id: '/calendar_/public'
      path: '/calendar/public'
      fullPath: '/calendar/public'
      preLoaderRoute: typeof CalendarPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar_/planning': {
      id: '/calendar_/planning'
      path: '/calendar/planning'
      fullPath: '/calendar/planning'
      preLoaderRoute: typeof CalendarPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/meetings/': {
      id: '/elder/meetings/'
      path: '/'
      fullPath: '/elder/meetings/'
      preLoaderRoute: typeof ElderMeetingsIndexRouteImport
      parentRoute: typeof ElderMeetingsRoute
    }
    '/elder/meetings/$meetingId': {
      id: '/elder/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/elder/meetings/$meetingId'
      preLoaderRoute: typeof ElderMeetingsMeetingIdRouteImport
      parentRoute: typeof ElderMeetingsRoute
    }
    '/calendar_/planning/review': {
      id: '/calendar_/planning/review'
      path: '/review'
      fullPath: '/calendar/planning/review'
      preLoaderRoute: typeof CalendarPlanningReviewRouteImport
      parentRoute: typeof CalendarPlanningRoute
    }
    '/calendar_/planning/$submissionId': {
      id: '/calendar_/planning/$submissionId'
      path: '/$submissionId'
      fullPath: '/calendar/planning/$submissionId'
      preLoaderRoute: typeof CalendarPlanningSubmissionIdRouteImport
      parentRoute: typeof CalendarPlanningRoute
    }
    '/api/google/oauth-callback': {
      id: '/api/google/oauth-callback'
      path: '/api/google/oauth-callback'
      fullPath: '/api/google/oauth-callback'
      preLoaderRoute: typeof ApiGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sunday-review-nudge': {
      id: '/api/public/hooks/sunday-review-nudge'
      path: '/api/public/hooks/sunday-review-nudge'
      fullPath: '/api/public/hooks/sunday-review-nudge'
      preLoaderRoute: typeof ApiPublicHooksSundayReviewNudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/action-items-digest': {
      id: '/api/public/hooks/action-items-digest'
      path: '/api/public/hooks/action-items-digest'
      fullPath: '/api/public/hooks/action-items-digest'
      preLoaderRoute: typeof ApiPublicHooksActionItemsDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ElderMeetingsRouteChildren {
  ElderMeetingsMeetingIdRoute: typeof ElderMeetingsMeetingIdRoute
  ElderMeetingsIndexRoute: typeof ElderMeetingsIndexRoute
}

const ElderMeetingsRouteChildren: ElderMeetingsRouteChildren = {
  ElderMeetingsMeetingIdRoute: ElderMeetingsMeetingIdRoute,
  ElderMeetingsIndexRoute: ElderMeetingsIndexRoute,
}

const ElderMeetingsRouteWithChildren = ElderMeetingsRoute._addFileChildren(
  ElderMeetingsRouteChildren,
)

interface ElderRouteChildren {
  ElderArchiveRoute: typeof ElderArchiveRoute
  ElderMeetingsRoute: typeof ElderMeetingsRouteWithChildren
  ElderPastoralCareRoute: typeof ElderPastoralCareRoute
  ElderSettingsRoute: typeof ElderSettingsRoute
  ElderIndexRoute: typeof ElderIndexRoute
}

const ElderRouteChildren: ElderRouteChildren = {
  ElderArchiveRoute: ElderArchiveRoute,
  ElderMeetingsRoute: ElderMeetingsRouteWithChildren,
  ElderPastoralCareRoute: ElderPastoralCareRoute,
  ElderSettingsRoute: ElderSettingsRoute,
  ElderIndexRoute: ElderIndexRoute,
}

const ElderRouteWithChildren = ElderRoute._addFileChildren(ElderRouteChildren)

interface CalendarPlanningRouteChildren {
  CalendarPlanningSubmissionIdRoute: typeof CalendarPlanningSubmissionIdRoute
  CalendarPlanningReviewRoute: typeof CalendarPlanningReviewRoute
}

const CalendarPlanningRouteChildren: CalendarPlanningRouteChildren = {
  CalendarPlanningSubmissionIdRoute: CalendarPlanningSubmissionIdRoute,
  CalendarPlanningReviewRoute: CalendarPlanningReviewRoute,
}

const CalendarPlanningRouteWithChildren =
  CalendarPlanningRoute._addFileChildren(CalendarPlanningRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DecisionsRoute: DecisionsRoute,
  ElderRoute: ElderRouteWithChildren,
  FinanceRoute: FinanceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MeetingRoute: MeetingRoute,
  MissionsRoute: MissionsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  SundayReviewRoute: SundayReviewRoute,
  TrendsRoute: TrendsRoute,
  UsersRoute: UsersRoute,
  CalendarPlanningRoute: CalendarPlanningRouteWithChildren,
  CalendarPublicRoute: CalendarPublicRoute,
  ApiGoogleOauthCallbackRoute: ApiGoogleOauthCallbackRoute,
  ApiPublicHooksActionItemsDigestRoute: ApiPublicHooksActionItemsDigestRoute,
  ApiPublicHooksSundayReviewNudgeRoute: ApiPublicHooksSundayReviewNudgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
