/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SundayReviewRouteImport } from './routes/sunday-review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGoogleOauthCallbackRouteImport } from './routes/api/google.oauth-callback'
import { Route as ApiPublicHooksSundayReviewNudgeRouteImport } from './routes/api/public/hooks.sunday-review-nudge'
import { Route as ApiPublicHooksActionItemsDigestRouteImport } from './routes/api/public/hooks.action-items-digest'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayReviewRoute = SundayReviewRouteImport.update({
  id: '/sunday-review',
  path: '/sunday-review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleOauthCallbackRoute = ApiGoogleOauthCallbackRouteImport.update({
  id: '/api/google/oauth-callback',
  path: '/api/google/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSundayReviewNudgeRoute =
  ApiPublicHooksSundayReviewNudgeRouteImport.update({
    id: '/api/public/hooks/sunday-review-nudge',
    path: '/api/public/hooks/sunday-review-nudge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksActionItemsDigestRoute =
  ApiPublicHooksActionItemsDigestRouteImport.update({
    id: '/api/public/hooks/action-items-digest',
    path: '/api/public/hooks/action-items-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/sunday-review': typeof SundayReviewRoute
  '/users': typeof UsersRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/hooks/action-items-digest': typeof ApiPublicHooksActionItemsDigestRoute
  '/api/public/hooks/sunday-review-nudge': typeof ApiPublicHooksSundayReviewNudgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/sunday-review': typeof SundayReviewRoute
  '/users': typeof UsersRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/hooks/action-items-digest': typeof ApiPublicHooksActionItemsDigestRoute
  '/api/public/hooks/sunday-review-nudge': typeof ApiPublicHooksSundayReviewNudgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/meeting': typeof MeetingRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/sunday-review': typeof SundayReviewRoute
  '/users': typeof UsersRoute
  '/api/google/oauth-callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/hooks/action-items-digest': typeof ApiPublicHooksActionItemsDigestRoute
  '/api/public/hooks/sunday-review-nudge': typeof ApiPublicHooksSundayReviewNudgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/finance'
    | '/login'
    | '/meeting'
    | '/missions'
    | '/settings'
    | '/sunday-review'
    | '/users'
    | '/api/google/oauth-callback'
    | '/api/public/hooks/action-items-digest'
    | '/api/public/hooks/sunday-review-nudge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/finance'
    | '/login'
    | '/meeting'
    | '/missions'
    | '/settings'
    | '/sunday-review'
    | '/users'
    | '/api/google/oauth-callback'
    | '/api/public/hooks/action-items-digest'
    | '/api/public/hooks/sunday-review-nudge'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/finance'
    | '/login'
    | '/meeting'
    | '/missions'
    | '/settings'
    | '/sunday-review'
    | '/users'
    | '/api/google/oauth-callback'
    | '/api/public/hooks/action-items-digest'
    | '/api/public/hooks/sunday-review-nudge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  MeetingRoute: typeof MeetingRoute
  MissionsRoute: typeof MissionsRoute
  SettingsRoute: typeof SettingsRoute
  SundayReviewRoute: typeof SundayReviewRoute
  UsersRoute: typeof UsersRoute
  ApiGoogleOauthCallbackRoute: typeof ApiGoogleOauthCallbackRoute
  ApiPublicHooksActionItemsDigestRoute: typeof ApiPublicHooksActionItemsDigestRoute
  ApiPublicHooksSundayReviewNudgeRoute: typeof ApiPublicHooksSundayReviewNudgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-review': {
      id: '/sunday-review'
      path: '/sunday-review'
      fullPath: '/sunday-review'
      preLoaderRoute: typeof SundayReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth-callback': {
      id: '/api/google/oauth-callback'
      path: '/api/google/oauth-callback'
      fullPath: '/api/google/oauth-callback'
      preLoaderRoute: typeof ApiGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sunday-review-nudge': {
      id: '/api/public/hooks/sunday-review-nudge'
      path: '/api/public/hooks/sunday-review-nudge'
      fullPath: '/api/public/hooks/sunday-review-nudge'
      preLoaderRoute: typeof ApiPublicHooksSundayReviewNudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/action-items-digest': {
      id: '/api/public/hooks/action-items-digest'
      path: '/api/public/hooks/action-items-digest'
      fullPath: '/api/public/hooks/action-items-digest'
      preLoaderRoute: typeof ApiPublicHooksActionItemsDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  MeetingRoute: MeetingRoute,
  MissionsRoute: MissionsRoute,
  SettingsRoute: SettingsRoute,
  SundayReviewRoute: SundayReviewRoute,
  UsersRoute: UsersRoute,
  ApiGoogleOauthCallbackRoute: ApiGoogleOauthCallbackRoute,
  ApiPublicHooksActionItemsDigestRoute: ApiPublicHooksActionItemsDigestRoute,
  ApiPublicHooksSundayReviewNudgeRoute: ApiPublicHooksSundayReviewNudgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
